name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get repository name
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Write .env
        env:
          PROXY_GITHUB_AUTH_TOKEN: ${{ secrets.PROXY_GITHUB_AUTH_TOKEN }}
        run: |
          echo "$PROXY_GITHUB_AUTH_TOKEN" | base64 --decode | echo "PROXY_GITHUB_AUTH_TOKEN=$(tee)" >> /home/runner/work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/.env
          echo $(cat /home/runner/work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/.env)
      - name: Set npm auth token
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "Home: $HOME"
          echo "Project working directory: $GITHUB_WORKSPACE"
          echo "$NPM_AUTH_TOKEN" | base64 --decode | echo "//registry.npmjs.org/:_authToken=$(tee)" >> /home/runner/work/${{ env.REPOSITORY_NAME }}/${{ env.REPOSITORY_NAME }}/.npmrc
          cat $GITHUB_WORKSPACE/.npmrc
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hoppingmode-web-api:latest
